# for Arnold Module

ARNOLD_PHRASES = [
    "It's showtime, {}!",
    "Alright everyone, chill",
    "Allow me to break the ice, {}",
    "{}, I need your clothes, your boots and your motorcycle",
    "{}, now listen to me very carefully",
    "{}, you, are not you. You're me",
    "{}, wrong. *shot to the head*",
    "{}, I'm going to ask you a bunch of questions, and I want to have them answered immediately",
    "Ha! Crom laughs at your Four Winds",
    "You're a funny guy, {}, I like you. That's why I'm going to kill you last",
    "Bullshit, {}",
    "That's bullshit, {}",
    "C'mon, don't bullshit me, {}",
    "You set us up, {}! It's all bullshit! All of it!!",
    "Talk to the hand, {}",
    "*shirtless, wielding knife* Come on {}. Let's party",
    "Enough talk! *throws knife into {}'s chest*",
    "Into the boat, {}!",
    "Into the tunnel, {}!",
    "GET TO THE CHOPPAAAAAAAA, {}",
    "Hello, {}! One of us is in deeeep trouble",
    "I'm pregnant, {}",
    "*grabs {} by the collar* STOP... CHEERING ME UP!",
    "No problemo, {}",
    "Grant me revenge, {}! And if you do not listen, then the hell with you!",
    "The hell you will, {}...",
    "The hell with you, {}",
    "Who the hell are you, {}??",
    "Hey, you want to be a farmer? Here's a couple of acres. *kicks {} across the street*",
    "*kicks down door* Knock knock, {}",
    "You're fired, {}. *shoots missile into helicopter*",
    "*shoots {} in face* You're luggage",
    "*ice cream truck explodes* Iced that guy... to cone a phrase",
    "*car crashes into cola billboard* Well that hit the spot",
    "To be. Or not to be... Not to be, {}. *lights cigar as building expdlodes*",
    "Doesn't anyone stay dead anymore, {}?",
    "Let's... kick some ice, {}",
    "This is war, {}",
    "If it bleeds... we can kill it, {}",
    "Now this is the plan, {}: get your ass to Mars",
    "What killed the dinosaurs, {}? The ice age!",
    "Crom!",
    "Frosty?",
    "Mac! MAAAAAAAC!",
    "The riddle... of steel!",
    "Bring the toy back, {}, bring the toy back to the carpet, bring it back to the carpet!!",
    "Take your toy back to the carpet, {}. TAKE IT BACK!!",
    "*choking {}* My name... is not Quaid!",
    "I don't know what the problem is. {}, but I'm sure it can be solved without resorting to violence",
    "Feel how soft my skin is, {}!",
    "*surprised* You're bleeding, {}!",
    "Ok, but make it quick, {}. My horse is getting tired",
    "I need a vacation, {}",
    "Shit, {}!",
    "I'm a cybernetic organism, {}, living tissue over a metal endoskeleton",
    "Come with me if you want to live, {}",
    "Danger is my trade, {}",
    "{}, I'm the famous comedian, Arnold Brawnschwaigger!",
    "{}, now remember, I could break your neck like a chicken's",
    "FREEZE IN HELL BATMAAAAAN!",
    "You killed my father, {}. Big mistake",
    "{}, you've just been erased",
    "{}, you are TERMINATED!",
    "When the governor gets here, call me, {}",
    "I eat green berets for breakfast. {}. And right now... I'm VERY HUNGRY",
    "Ha hahaha ha ha! {}, you think this is the real Quaid?",
    "You're not sending ME to the cooler, {} ...",
    "I have my orders, {}",
    "No sequel for you, {}. *shoots explosives*",
    "I'll be back, {}",
    "BWA HAHAHAHAHA, {}!",
    "Ahahahaha, {}!",
    "Get down, {}!",
    "Hasta la vista. {}",
    "Come on, {}! You got what you want. Give those people air!!",
    "{}, what about the guy you lobotomized? Did he get a refund?",
    "Relax, {}. You'll live longer",
    "Do it, {}. DO IT! Come on, kill me, I'm here! COME ON, DO IT NOW, KILL MEEEE!!",
    "{}, ARRRRRRRGGGGGGGH",
    "{}, GAAAAAAGGHHHHHH!",
    "{}, WWWAAAAAGGHHHHH",
    "{}, AAAAARRRRRGGGHHHHHHHHH",
    "Put the cookie down, {}. NOW!!",
    "Cookies, {}? Who told you you could eat my cookies?",
    "{}, could I speak to the drug dealer of the house please? It's a beautiful day and we're out killing drug dealers",
    "Hercules doesn't need any money, {}",
    "If I'm not me, who the hell am I, {}?",
    "{}, you have no respect for logic. And I have no respect for those with no respect to logic",
    "{}, your confusion is not rational. She is a healthy female of breeding age",
    "What the hell is going on here? There's someone in my house, eating my birthday cake, and it's not me",
    "I saved a life today, what the hell did you do, {}?",
    "You took my father's sword, {}!",
    "What's the matter, {}? The CIA got you pushing too many pencils?",
    "I remember days like this, {}, when my father took me to the forest and we ate wild blueberries",
    "If revenge is a dish best served cold... then put on your Sunday's finest, it's time to feast, {}!",
    "Try to stay dead this time, {}",
    "{}, you have striked Hercules",
    "It's just a doll, {}... it's just a stupid little plastic doll",
    "Kill the heroes, {}! Yes, kill them, kill them, yes!",
    "You picked the wrong day, {}",
    "It's turbo time, {}",
    "Gee, {}, did you make a movie mistake? You forgot to reload the damn gun!"
]