# for LEGO Movie Module

LEGO_QUOTES = [
    "He is coming... cover your butt.",
    "You've hidden the Kragle well old man. Robots! Destroy him.",
    "Your robots are no match for a Master Builder, for I see everything!",
    "Ahh Haa Haa! Now my evil power will be unlimited. Can you feel me?!",
    "One day a talented lass or fellow, a special one, with face of yellow, will make the Piece of Resistance found, from it's hiding refuge underground. And with a noble army at the helm, this Master Builder will thwart the Kragle and save the realm, and be the greatest, most interesting, most important person of all times. All this is true because it rhymes.",
    "All this is true because it rhymes.",
    "Ohh! Wow! That was a great inspiring legend.. that you made up.",
    "What a load of hippie dippie baloney.",
    "Goooood morning apartment. Good morning doorway, morning wall, morning ceiling, good morning floooorr. Ready to start the day!",
    "Ahh, here it is. Instructions to fit in, have everybody like you and always be happy!",
    "Step 1: Breathe.",
    "Step 2: Greet the day, smile and say: \"Good morning, city!\"",
    "Step 3: Exercise. Jumpin' Jacks, hit 'em!.. 1... 2... 3... Haha, I am so pumped up!",
    "Step 4: Shower... and always be sure to keep the soap out of yo- AAHHHHH!",
    "Wear clothes. Ooops! Almost forgot that one!",
    "Hey Planty, what'd you wanna do this morning? Watch TV? Me too!",
    "Hi, I'm President Business, president of the Octan corporation and the world. Let's take special care to follow the instructions, or you'll be put to sleep. And don't forget Taco Tuesday is coming up! That's the day everyone gets a free taco and my love! You have a great day everyone.",
    "You have a great day too President Business. Man, he's such a cool guy, I always wanna hear more of- Wait, did he say put to sleep?!",
    "Honey, where are my paaaaannts?",
    "What was I just thinkin'? I don't care :D",
    "Everything is awesome! Everything is cool when you're part of a team. Everything is awesooooomme when you're living a dreeeam.",
    "Gooooooo sports team!",
    "Hey guys, watch me drill this down!",
    "I think I heard a \"Whoosh\".",
    "Hey pal, I hate to tell you this but ahh, I don't think you're supposed to be down here...",
    "Yeah, the rules specifically state: work site closes at six, its a hard hat area only, that's not official safety orange...",
    "If you see anything weird report it immediately. Well! I guess I'm just going to have to report yoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
    "I dunno what to do... I don't have my instructions...",
    "Touch the piece...",
    "I feel like maybe I should touch that...",
    "Playin' dumb Master Builder?",
    "You're a LIAR!",
    "I watch a lot of cop shows on TV.. isn't there supposed to-... isn't there supposed to be a good cop?",
    "Hi buddy! I'm your friendly neighourhood police officer! Would you like a glass of water? TOO BAD!",
    "Security cameras picked this up. You were found at the construction site, convulsing with a strange piece.",
    "It's not my fault! I have no idea how this thing got on my back!",
    "Of course buddy, we believe you.",
    "I believe you too. You see the quotations I'm making with my claw hands? It means I DOn't believe you.",
    "Predsident Business is going to end the world? But he's such a good guy.. and Octan, they make good stuff! Music, dairy products, coffee, TV shows, surveillance systems, all history books, voting machines... wait a minute.",
    "That guy is not a criminal mastermind.",
    "When you say {} I go HA HA HAHA! When you say the other guy, I go... :|",
    "I can't break him, take him to the melting chamber!",
    "You're going to melt me?! Am I gonna die?!",
    "Yes, we've told him he's going to live, but ahh.. we're lying to him.",
    "Come with me if you wanna not die.",
    "Hi everybody! How is the melting going- Hey, hey, heeeyyy!",
    "Oh sir you're brilliant! We'll build a motorcycle out of the alley way.",
    "It's brilliant sir that you've pretended to be a useless nobody, but you can drop the act with me its cool.",
    "All units, cut him off on Elm, NOW!... or, whenever you can.",
    "You found the Piece of Resistance and the prophecy states that you are the most important, most talented, most interesting and most extraordinary person in the universe. That's you isn't it?",
    "That was incredible, you're even better than the prophecy said you'd be!",
    "I can't do this! That is against the instructions!",
    "Darn, darn, darn, darny, DARN!",
    "You're not the special, you lied to me!",
    "I know what a Master Builder is, why don't you tell me what it is, that way I could see if you're right.",
    "Oh my G. O. S. H.",
    "By the way I have a boyfriend. Its super serious and you do not want to mess with him. So don't get any ideas.",
    "I never have any ideas.",
    "Hey ahh listen do you think you could explain to me like why I'm dressed like this and what those big words in the sky were all about and where we are.. in.. time?",
    "Blah, blah, blah proper name, place name, back story stuff. I'm so pretty, I like you but I'm angry with you for some reason.",
    "Great! I think I got it. But just in case... tell me the whole thing again because I wasn't listening.",
    "We're trying to find the fugitive, but his face is so generic it matches every other face in our database.",
    "Diabolical.",
    "I love everyone in this room!",
    "Would you cancel my two o'clock? This next meeting could run a little bit.. deadly.",
    "This one is the cloak of Band Ai'd. I hear its super painful to take off. You wanna try it on?",
    "It makes me.. just wanna pickup whoever is standing closest to me.. and just throw them through this window.. out into the INFINITE. ABYSS. of NOTHINGNESS!... I wanna do it sooo baadd.",
    "Robots! Bring me the fleece crested sceptre of Cu Tee'p and the Po'leesh remover of Na'eel.",
    "Howdy I'm a cowboy! Bang bang, bang bang bang, shoot shoot shoot, bullet bullet gun, zap zap zap pow zap pow! What're they lookin' at?",
    "You have a very weirdly decorated place.",
    "The prophecy states that you are the special. The embodiment of good, foiler of evil, the most talented, most brilliant, most important person in the universe.",
    "Just given what's around you, build something simple... like an awesome race car.",
    "Wooooaah are we inside my brain right now? It's biiig I must be smart.",
    "That is literally the dumbest thing I have ever heard.",
    "That idea is just the worst.",
    "{} , your mind is already so prodigiously empty that there is nothing in it to clear away in the first place. With proper training, you could become a great Master Builder.",
    "All you have to do is to believe... then you will see everything.",
    "Freeze, Turkey's!",
    "We need to attach the wheel to something that spins around.",
    "Rest in pieces.",
    "Well, for what its worth, this has been about the greatest 15 minutes of my life.",
    "BATMAN!!!",
    "I'm Batman.",
    "Batman huh? Where'd you guys meet?",
    "Police to meet you Bad Cop.",
    "Guess what you big dumb baby? Your car is a baby carriage.",
    "Oh nooo your boyfriend's gone..",
    "Hey babe. Let's hold hands.",
    "Soo uhhh, hey guys, I think we're about to crash into the sun.",
    "Yeah, but it's gonna look really cool.",
    "Ahh, is this Cloud Cuckoo Land? I don't see any clouds or.. Cuckoo's..",
    "This is Middle Zealand. A wonderous land full of knights, castles, mutten, torture weapons, poverty, leeches, illiteracy, and umm... DRAAAGGONNNNSS!!",
    "Yeah, yeah anyway. You guys have gotta checkout these new subwoofers I got installed in the back. I call them \"The Dogs\". Listen to 'em bark!",
    "This is a song I wrote for {} . Darkness! It's about how I'm an orphan. No parents!",
    "This is real music {} . Batman's a true artist.. dark, brooding.",
    "Yeah, well I can be dark and brooding too - Ohh, Look guys a rainbow!",
    "I just need to give the secret knock...",
    "I'm just gonna come right out, I.. have no idea what is going on, or what this place is.. at all.",
    "Hiiiii! I am Princess {} , and I welcome you all to Cloud Cuckoo Land!",
    "So there are no signs or anything.. how does anyone know what not to do?",
    "Here in Cloud Cuckoo Land there are no rules! There's no government, no babysitters, no bedtimes, no frownie faces, no bushy mustaches and no negativity of any kind!",
    "I hate this place..",
    "Any idea is a good idea, except the not happy ones. Those get pushed down deep inside where you will never, ever, ever, EVER! Fiiind theeem :)",
    "D-Didn't Krypton blow up?",
    "The special will now give an eloquent speech... Go ahead man, you got this.",
    "Really hard?! Wiping your butt with a hook for a hand is REALLY HARD!",
    "I had to replace every part of my once strapping, virial pirate body with this useless hunk of junk ye see before ye.",
    "Yes, it's true. I may not be a Master Builder.. I may not have a lot of experience, fighting or leading or coming up with plans.. or have ideas in general.",
    "{} , you bring your space chair right back here!",
    "Well, you were right about him being a ding dong.",
    "Oh oh! It's the bad guys.",
    "Ya'll ready for this?!... Oh no! They were ready for that!",
    "I super hate you..",
    "Hey! I'm Ben but you can call me Benny, and I can build a spaceship. Watch this.. spaceship, spaceship, spaaaceship, spaceship, spaceship!",
    "That's okay. I didn't really wanna.. build a spaceship anyway.. that's cooool..",
    "Bat Submarine! Patent pending.",
    "If anybody has black parts I need them okay. I only work in black... and sometimes very very dark gray.",
    "Eww. Get your retro space stuff out of my area.",
    "Oh no.. I feel something inside.. it's like.. the opposite of HAPPINESS! I must.. stay positive. Ahhh, bubblegums.. Butterflies!.. Oh! Cotton candy!",
    "You are so disappointing on so many levels.",
    "Greetings all. Welcome to my THINK TANK!",
    "Does anybody have some Kryptonite that they could get me?",
    "It's kinda hard not to hear when you're yelling everything.",
    "What's the last thing Lord Business would expect us to do? Build a spaceship? Kill a chicken? Marry a marshmellow? Why this! Ha-ha-how ya gonna keep 'em, down on the farm! down on the- No! It's follow the instructions.",
    "She be a fine speech there laddy.",
    "Somebody get me some markers!... Some construction paper!... And some glitter glue!",
    "One of those sounds awesome to me.",
    "So not.. special spaceship that I'm.. I'm building for all of you right now?",
    "Oooo you're really letting the oxygen out of my tank here.",
    "Hold on Han. This might be the right galaxy after all, because I see a heavenly body.",
    "Well he's just as blind as.. a.. guy.. who's eyes.. just.. s-s-stopped working.",
    "Is that last name butt, first name yourrr.. OH MY GOSH!",
    "Pow! Wham! Ka-zab! Eh, eh, oh, eh... First try!",
    "{} , that was awesome.",
    "First law of the sea. Never place your rear end on a pirates face."
    "Cooool, talking computer!",
    "There are no movies in your area with that title.",
    "Bruce Wayne? Hahaha, who's that? Sounds like a cool guy.",
    "Sure, sure, sure... let's go with that.",
    "Untz, untz, untz, untz untz untz, untz, untz, untz untz untz, untz, untz, everything is awesome!",
    "Business, business, business.. numbers. Is this working? YAAAAYYYY!",
    "Don't worry Dad I read your dumb instructions, stop yelling at me.",
    "Downloading latests episodes of \"Where are my pants?\"",
    "We'll wing it... that's a bat pun...",
    "Searching for Albanian restaurants...",
    "Which phrase would you like me to undermine?",
    "Acceptable work, {} .",
    "You see {} , a corrupted spirit is no match for the purity of imaginat-",
    "The prophecy... I made it up. It's not true.",
    "You must listen... for what I am about to tell you.. will change the course of history...",
    "As unspecial as I am, you are a thousand billion times more unspecial than me.",
    "Must be weird... One minute you're the most special person in the universe... the next minute you're NOBODY.",
    "It's not personal. It's just business... Lord Business. Ciao!",
    "Don't worry about this big, black, monolith thing that's blocking out the sun. What you need to worry about is this question that I'm about to ask you... Who wants a TACO?!",
    "Alright everyone, act normal... Now, FREEZE!",
    "Commencing micro-management.",
    "{} , you'll... you'll think of something won't you? Just like you always do.",
    "The only thing anyone needs to be special is to believe that you can be. I know that sounds like a cat poster, but its true.",
    "Nineteen eighties something technology? Now you're talking!",
    "Hey everybody. You don't know me but I'm on TV so... you can trust me.",
    "All of you have the ability inside you to be a ground breaker! And I mean literally, BREAK THE GROUND!",
    "I'll hold these guys off, you go schtop 'em. Yay!",
    "SPACESHIP!!!!",
    "What is going on?! You stop building that stuff! Just STOP IT!",
    "If only {} was here to see this. He'd say something adorable like...",
    "Why is the dragon on top of the luxury condo development?",
    "You accidentally... expertly, carefully took the top off that tower?",
    "But the way I'm using it makes it an adult thing.",
    "That's a suggestion. They have to put that on there.",
    "He's not just a construction worker, {} . He's the hero!",
    "If I could get the attention of the smaller creature...",
    "Believe! I know it sounds like a cat poster, but its true.",
    "Sorry, street.",
    "I can see everything... I am a Master Builder!",
    "Stay positive... Stay. Positive... Ahhh, forget it! AARRRGGGHHH!!! You all need to be more friendlllyyy!!!",
    "Back from the dead, {} ? Skeletrons, get him!",
    "What is that? Is it super small? I don't see anything.",
    "Okay. What I see are people, inspired by each other and by you. People taking what you made and making something new out of it.",
    "You don't have to be the bad guy. You are the most talented, most interesting, and most extraordinary person in the universe. And you are capable of amazing things, because you are the special. And so am I, and so is everyone. The prophecy is made up but its also true, it's about all of us. Right now its about you, and you still.. can change everything.",
    "Be careful. I have been told, it might explode.",
    "No, wait, {} . He's the hero you deserve.",
    "We are from the planet Duplo, and we are here to.. destroy you."
]