# for LEGO Movie Module

LEGO_QUOTES = [
    "{}, We are from the planet Duplo, and we're here to destroy you.",
    "{}, To the Batmobile!",
    "{}, To the Invisible Jet!",
    "{}, If this relationship is going to work out between us I need to feel free to party with a bunch of strangers whenever I feel like it. I will text you.",
    "{}, Darn, darn, darn, darny-darn!",
    "{}, You don't have to be the bad guy. You are the most talented, most interesting, and most extraordinary person in the universe. And you are capable of amazing things. Because you are the Special. And so am I. And so is everyone. The prophecy is made up, but it's also true. It's about all of us. Right now, it's about you. And you... still... can change everything.",
    "{}, You are the most talented, most interesting, and most extraordinary person in the universe.",
    "{}, The prophecy is made up, but it's also true. It's about all of us. Right now, it's about you. And you... still... can change everything.",
    "{}, Uh, guys? We're about to crash into the sun.",
    "{}, Yeah, but it's gonna look really cool.",
    "{}, Playing dumb, Masterbuilder?",
    "{}, Oh, so you've never heard of the prophecy? Or the Special?",
    "{}, Look, um... I watch a lot of cop shows on TV... isn't there supposed to be a-... Isn't there supposed to be a good cop?",
    "{}, Oh yes, but we're not done yet.",
    "{}, Hi, buddy! I'm your friendly neighborhood police officer! Would you like a glass of water?",
    "{}, You know, I don't want to spoil the party but, does anyone notice that we're stuck in the middle of the ocean on this couch?",
    "{}, Do you know what kind of sunburn I'm going to get? None, 'cause I'm covered in latex, but you guys are going to get seriously fried.",
    "{}, Don't worry, Superman, I'll get you out of there!",
    "{}, Oh, my gosh, my hands are stuck. My legs are stuck as well.",
    "{}, I super hate you.",
    "{}, I only work in black and sometimes very, very dark grey.",
    "{}, All I'm asking for is total perfection.",
    "{}, We are entering your mind...",
    "{}, To prove that you have the unlocked potential to be a Master Builder.",
    "{}, Whoa, are we inside my brain right now? It's big. I must be smart.",
    "{}, I'm not hearing a whole lot of activity in here.",
    "{}, I don't think he's ever had an original thought... in his life.",
    "{}, One time I wanted a bunch of my friends over to watch TV, not unlike this TV that just showed up magically. And not everybody can fit on my one couch, and I thought to myself, well, what if there's such a thing as a bunkbed but as a couch? Introducing the double decker couch! So everyone could watch TV together and be buddies!",
    "{}, That's literally the dumbest thing I ever heard.",
    "{}, Please, {}, let me handle this. That idea is just the worst.",
    "Is that a last name Butt, first name Your...?",
    "{}, Pow! Wham! Kezap! First try!",
    "{}, That's real music, {}. It's dark and brooding.",
    "{}, Hey, I can be dark and brooding too - Guys, look, a rainbow!",
    "{}, Hi, I'm President Business, president of the Octan corporation and the world. Let's take extra care to follow the instructions or you'll be put to sleep, and don't forget Taco Tuesday's coming next week.",
    "{}, Disable the shield! Come on! You are undermining me!",
    "{}, Which phrase would you like me to underline?",
    "{}, Be ye disabling of yond shield.",
    "{}, Then I guess we'll just have to wing it... That's a bat pun.",
    "{}, Hey, uh, listen. Do you think you can explain to me why I'm dressed like this? And what those big words in the sky were all about? And, like, where we are... in time?",
    "{}, Your home, Bricksburgh, is one of many realms in the universe. There's also this one, Pirates Cove, Knights Club, Vikings Landing, Clown Town, and a bunch of others we don't even mention. Lord Business, or as you think you know him, President Business, stole the Kragl, the most powerful object in the universe...",
    "{}, Blah, blah, blah. Proper name. Place name. Backstory stuff...",
    "{}, I'm so pretty. I like you. But I'm angry with you for some reason...",
    "{}, Great. I think I got it. But just in case... tell me the whole thing again, I wasn't listening.",
    "{}, We'd rather he die than give it to you.",
    "{}, I... would not rather he died.",
    "{}, A house divided against itself... would be better than this!",
    "{}, Come with me if you want to not die.",
    "{}, Get off my train.",
    "{}, I have no experience fighting, leading or making plans...",
    "{}, WIPING YER BUM WITH A HOOK FOR A HAND IS REALLY HARD! THIS BE IMPOSSIBLE!",
    "{}, He's coming, cover your butts.",
    "{}, I'm just gonna come right out, I have no idea what's going on or what this place is at all.",
    "{}, Hi! I am Princess {}, and I welcome you all to Cloud Cuckoo Land!",
    "{}, So there are no signs on anything. How does anyone know what not to do?",
    "{}, Here in Cloud Cuckoo Land, there are no rules: There's no government, no baby sitters, no bedtimes, no frowny faces, no bushy mustaches, and no negativity of any kind.",
    "{}, You just said the word \"no\" like a thousand times.",
    "{}, And there's also no consistency.",
    "{}, I hate this place.",
    "{}, Any idea is a good idea except the non-happy ones. Those we push down deep inside where you'll never, ever, ever, EVER find them!",
    "{}, Yes, I am... I think.",
    "{}, One day, a talented lass or fellow, a special one with face of yellow, will make the Piece of Resistance found from it's hiding refuge underground, and with a noble army at the helm, this Master Builder will thwart the Kragle and save the realm, and be the greatest, most interesting, most important person of all times. All this is true because it rhymes.",
    "{}, Spaceship!",
    "{}, You were found at the construction site convulsing with a strange piece.",
    "{}, That's disgusting!",
    "{}, My fellow Master Builders. Including but not limited to Robin Hood, Mermaid Lady, Gandalf, Swamp Creature, 1980s Something Space Guy, the 2002 NBA All Stars and Wonder Woman.",
    "{}, Hello.",
    "{}, You have traveled far to be here for a moment of great import. We have learned that Lord Business plans to unleash a fully-weaponized Kragle on Taco Tuesday to end the world as we know it.",
    "{}, Please calm yourselves Green Ninja, Milhouse, Nice Vampire, Michelangelo, Michelangelo, and Cleopatra. There is yet one hope. The Special has arisen.",
    "{}, Have the young man step forward.",
    "{}, As you wish, Dubbledore.",
    "{}, I'm Gandalf!",
    "{}, It's pronounced Dumbledore.",
    "{}, Dubbledore?",
    "{}, No, Dumbledore.",
    "{}, I thought you said Dubbledore.",
    "{}, Vitruvius!",
    "{}, Ah, we gotta write all that down 'cause I'm not gonna remember any of it, but here we go.",
    "{}, The Special will now give an eloquent speech.",
    "{}, Go ahead man, you got this.",
    "{}, Today will not be known as Taco Tuesday. It will be known as freedom Friday... but still on a Tuesday!",
    "{}, I watched Lord Business' forces completely overlook it. Which means we need more ideas like it! Ideas so dumb and bad that no one would ever think they could possibly be useful.",
    "{}, Oh, thank you.",
    "{}, Oh. Thank you.",
    "{}, You know the rules, this isn't a toy!",
    "{}, Um... it kind of is.",
    "{}, No, actually it's a highly sophisticated inter-locking brick system.",
    "{}, But we bought it at the toy store.",
    "{}, We did, but the way I'm using it makes it an adult thing.",
    "{}, The box for this one said \"Ages 8 to 14\"!",
    "{}, That's a suggestion. They have to put that on there.",
    "{}, Hey, I'm Ben! But you can call me Benny! And I can build a spaceship. Watch this. Spaceship! Spaceship! Spaceship! Spaceship! Spaceship!",
    "{}, Spaceship! Spaceship! Spaceship! Spaceship! Spaceship!",
    "{}, No! You can't. The skies are surrounded.",
    "{}, That's okay, I didn't really wanna build a spaceship. Anyway, that's cool.",
    "{}, this is my boyfriend. Batman.",
    "{}, I'm Batman.",
    "{}, That's your boyfriend?",
    "{}, Batman, huh? Where did you guys meet?",
    "{}, It's actually a funny story. Right, {}...?",
    "{}, Police to meet you, {}.",
    "{}! The pleasure is all mine!",
    "{}, Guess what, you big dumb baby? Your car is a baby carriage.",
    "{}, you had a vision.",
    "{}, I did?",
    "{}, MasterBuilders spend years training themselves to clear their minds enough to have even a fleeting glimpse of The Man Upstairs and yet, your mind is already so prodigiously empty that there is nothing in it to clear away in the first place. With proper training you could become a great MasterBuilder.",
    "{}, I am Ghost Vitruvius. Oooooh. {}, you didn't let me finish earlier because I died. The reason I made up the prophecy was because I knew that whoever found the piece could become the special. Because the only thing anyone needs to be special is to believe that you can be. I know that sounds like a cat poster but it's true. Look at what you did when you believed you were special. You just need to believe it some more.",
    "{}, The reason I made up the prophecy was because I knew that whoever found the piece could become the special.",
    "{}, Because the only thing anyone needs to be special is to believe that you can be. I know that sounds like a cat poster but it's true.",
    "{}, I know that sounds like a cat poster but it's true.",
    "{}, Look at what you did when you believed you were special. You just need to believe it some more.",
    "{}, But how could I just decide to believe that I'm special when I'm not?",
    "{}, Because the world depends on it. Ooooohh.",
    "{}, My sweet {}, come closer. You must know something about the prophecy.",
    "{}, The prophecy... I made it up.",
    "{}, I made it up. It's not true.",
    "{}, But that means I'm just... I'm not the special?",
    "{}, You must listen. What I'm about to tell you will change the course of history..."
]